// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type Conference struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	CashSupport sql.NullInt32  `json:"cash_support"`
	SchoolYear  sql.NullString `json:"school_year"`
}

type Department struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	FacultyID int32  `json:"faculty_id"`
}

type Faculty struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Group struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	ConferenceID int32  `json:"conference_id"`
	FacultyID    int32  `json:"faculty_id"`
}

type GroupSupervisor struct {
	ID            int32 `json:"id"`
	SupervisorID  int32 `json:"supervisor_id"`
	Role          int32 `json:"role"`
	GroupReportID int32 `json:"group_report_id"`
}

type Library struct {
	ID      int32          `json:"id"`
	Name    string         `json:"name"`
	Url     sql.NullString `json:"url"`
	OwnerID int32          `json:"owner_id"`
}

type Notification struct {
	ID   int32          `json:"id"`
	Name string         `json:"name"`
	Url  sql.NullString `json:"url"`
}

type StudentTopic struct {
	ID        int32 `json:"id"`
	StudentID int32 `json:"student_id"`
	TopicID   int32 `json:"topic_id"`
}

type Topic struct {
	ID           int32          `json:"id"`
	Name         string         `json:"name"`
	LectureID    int32          `json:"lecture_id"`
	FacultyID    int32          `json:"faculty_id"`
	Status       int32          `json:"status"`
	ResultUrl    sql.NullString `json:"result_url"`
	ConferenceID int32          `json:"conference_id"`
	GroupID      sql.NullInt32  `json:"group_id"`
	TimeStart    time.Time      `json:"time_start"`
	TimeEnd      time.Time      `json:"time_end"`
}

type TopicRegistration struct {
	ID        int32         `json:"id"`
	Name      string        `json:"name"`
	LectureID int32         `json:"lecture_id"`
	FacultyID int32         `json:"faculty_id"`
	Status    sql.NullInt32 `json:"status"`
	CreatedAt time.Time     `json:"created_at"`
}

type TopicResult struct {
	ID           int32   `json:"id"`
	Score        float64 `json:"score"`
	Comment      string  `json:"comment"`
	TopicID      int32   `json:"topic_id"`
	SupervisorID int32   `json:"supervisor_id"`
}

type User struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	HashPassword string `json:"hash_password"`
	Email        string `json:"email"`
	TypeAccount  int32  `json:"type_account"`
}

type UserInfo struct {
	ID          int32          `json:"id"`
	UserID      int32          `json:"user_id"`
	Name        string         `json:"name"`
	Email       string         `json:"email"`
	Phone       string         `json:"phone"`
	FacultyID   int32          `json:"faculty_id"`
	Degree      int32          `json:"degree"`
	YearStart   int32          `json:"year_start"`
	AvataUrl    sql.NullString `json:"avata_url"`
	Birthday    sql.NullString `json:"birthday"`
	BankAccount sql.NullString `json:"bank_account"`
}
