// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
)

type Department struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	FacultyID int64        `json:"faculty_id"`
	UserID    int64        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Faculty struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	UserID    int64        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Group struct {
	ID         int64        `json:"id"`
	TopicID    int64        `json:"topic_id"`
	LecturerID int64        `json:"lecturer_id"`
	TermID     int64        `json:"term_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}

type Lecturer struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	UserID    int64        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Reference struct {
	ID           int64        `json:"id"`
	ReferenceUrl string       `json:"reference_url"`
	Name         string       `json:"name"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdateAt     sql.NullTime `json:"update_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

type Status struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Student struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	UserID    int64        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type StudentGroup struct {
	GroupID   int64 `json:"group_id"`
	StudentID int64 `json:"student_id"`
}

type Term struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Topic struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	DepartmentID int64          `json:"department_id"`
	TimeStart    sql.NullTime   `json:"time_start"`
	TimeEnd      sql.NullTime   `json:"time_end"`
	Deadline     sql.NullTime   `json:"deadline"`
	StatusID     int64          `json:"status_id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
}

type User struct {
	ID         int64        `json:"id"`
	Username   string       `json:"username"`
	Password   string       `json:"password"`
	Email      string       `json:"email"`
	Permission int64        `json:"permission"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}
