// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: user_info.sql

package db

import (
	"context"
)

const getUserInfo = `-- name: GetUserInfo :one
SELECT user_id, name, description, avata_url, birthday, faculity_id, year_start, bank_account, phone, sex FROM "user_info"
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserInfo(ctx context.Context, userID int64) (UserInfo, error) {
	row := q.db.QueryRowContext(ctx, getUserInfo, userID)
	var i UserInfo
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.AvataUrl,
		&i.Birthday,
		&i.FaculityID,
		&i.YearStart,
		&i.BankAccount,
		&i.Phone,
		&i.Sex,
	)
	return i, err
}
