version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_SOURCE=postgresql://u7xfvwpftmunpstzixfb:C966Tikw9TVr5CT3oICZkPpOlMMqPQ@bpjvf0abkz3vn3j7p5qx-postgresql.services.clever-cloud.com:5432/bpjvf0abkz3vn3j7p5qx
    ports:
      - "8080:8080"
    entrypoint: ["/app/wait-for.sh", "bpjvf0abkz3vn3j7p5qx-postgresql.services.clever-cloud.com:5432", "--", "/app/start.sh"]
    command: ["/app/main"]