version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_SOURCE=postgres://thopham:Lk8UZozxGk0BfPfAdfjsjUsptsYtMcKu@dpg-cgkogb8rddleudvr9ee0-a.singapore-postgres.render.com/nckhdb
    ports:
      - "8080:8080"
    entrypoint: ["/app/wait-for.sh", "dpg-cgkogb8rddleudvr9ee0-a.singapore-postgres.render.com", "--", "/app/start.sh"]
    command: ["/app/main"]