version: '3.7'

services:
  db:
    container_name: "db"
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: nckh
      MYSQL_USER: admin
      MYSQL_PASSWORD: "secret"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
networks:
  default:
volumes:
  mysql_data: