###
GET http://localhost:8080/department/info
Authorization: Bearer v2.local.kc-P6wLzatf0V2ineZJqWcjbZJaWQEYJgFI1tGsU_FeHulLi4w04xLhWXyFa_Us2gE7O2zcOldbjtllOI3hUNyew0xjSGgHULHLSqJR-jq_SsrLtIVLFjvu_q67ZZbZ6F7WiumkQ7F1TVbzjkx1wsnLo9s3b9uyOEa5ueCXDjvUYB993m8fHhcCRgJZXLLWXWeEZs5Y4fZTVfeGyfcSmsPeji7Hd2H-ugTkvxjf_gjKY9jyJBWrK692HRMrmR0MMO2LSLzqWMIgwJUAO2NEbJ4k.bnVsbA

###
POST http://localhost:8080/user/login
Content-Type: "application/json"

{
    "username": "humgsv01",
    "password": "12345678"
}
###
GET http://localhost:8080/topics?page=1&&page_size=10
###
GET http://localhost:8080/departments?faculty_id=2
###
GET http://localhost:8080/faculties