GET http://localhost:8000/admin/user?user_type_id=1
###
POST http://localhost:8000/admin/user
Content-Type: application/json

{
    "username": "ChiDau",
    "password": 123,
    "user_type_id": 3
}
###
PUT http://localhost:8000/admin/user/4
Content-Type: application/json

{
    "username": "lão hạc33",
    "password": "1234a",
    "user_type_id": 1
}
###
DELETE http://localhost:8000/admin/user/3

###
GET http://localhost:8000/admin/faculty
###
POST http://localhost:8000/admin/faculty
Content-Type: application/json

{
    "name": "faculty 123",
    "user_id": 18
}
###
PUT http://localhost:8000/admin/faculty/1
Content-Type: application/json

{
    "name": "faculty 1235",
    "user_id": 2
}
###
DELETE http://localhost:8000/admin/faculty/1

###
GET http://localhost:8000/admin/department?name=Depart&&user_id=6&&faculty_id=5
###
POST http://localhost:8000/admin/department
Content-Type: application/json

{
    "name": "Department 123",
    "faculty_id": 22,
    "user_id": 20
}
###
PUT http://localhost:8000/admin/department/1
Content-Type: application/json

{
    "name": "Department 12355",
    "faculty_id": 5,
    "user_id": 6
}

###
GET http://localhost:8000/admin/lecture
###
POST http://localhost:8000/admin/lecture
Content-Type: application/json

{
    "name": "Lecture 123",
    "user_id": 30
}
###
PUT http://localhost:8000/admin/lecture/3
Content-Type: application/json

{
    "name": "Lecture 123",
    "user_id": 9
}
###
DELETE http://localhost:8000/admin/lecture/1





