// Code generated by goctl. DO NOT EDIT.
package types

type Result struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type User struct {
	ID          int64  `json:"id"`
	Username    string `json:"username"`
	Role        int64  `json:"role"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	Phone       string `json:"phone"`
	FacultyID   int64  `json:"faculty_id"`
	YearStart   int64  `json:"year_start"`
	Degree      int64  `json:"degree"`
	AvatarUrl   string `json:"avatar"`
	Birthday    string `json:"birthday"`
	BankAccount string `json:"bank_account"`
}

type LoginReq struct {
	Username string `json:"username"` //	username
	Password string `json:"password"` // 	password
}

type Token struct {
	RefreshToken string `json:"refreshToken"`
	AccessToken  string `json:"accessToken"`
}

type LoginRes struct {
	Result   Result `json:"result"`    // 	response result
	Token    Token  `json:"authToken"` // 	jwttoken for api
	UserInfo User   `json:"user"`      //  info user
}

type RegisterReq struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
	Name        string `json:"name"`
	Role        int64  `json:"role"`
	Email       string `json:"email"`
	Phone       string `json:"phone"`
	FacultyID   int64  `json:"faculty_id"`
	YearStart   int64  `json:"year_start"`
	Degree      int64  `json:"degree"`
	AvatarUrl   string `json:"avatar_url"`
	Birthday    string `json:"birthday"`
	BankAccount string `json:"bank_account"`
}

type RegisterRes struct {
	Result Result `json:"result"`
}

type GetUsersReq struct {
}

type GetUsersRes struct {
	Result Result `json:"result"`
	Total  int64  `json:"total"`
	Users  []User `json:"users"`
}
