// Code generated by goctl. DO NOT EDIT.
package types

type Result struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type User struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	TypeAccount int64  `json:"typeAccount"`
}

type LoginReq struct {
	Username string `json:"username"` //	username
	Password string `json:"password"` // 	password
}

type Token struct {
	RefreshToken string `json:"refreshToken"`
	AccessToken  string `json:"accessToken"`
}

type LoginRes struct {
	Result   Result `json:"result"`    // 	response result
	Token    Token  `json:"authToken"` // 	jwttoken for api
	UserInfo User   `json:"user"`      //  info user
}
