// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	eventTblFieldNames          = builder.RawFieldNames(&EventTbl{}, true)
	eventTblRows                = strings.Join(eventTblFieldNames, ",")
	eventTblRowsExpectAutoSet   = strings.Join(stringx.Remove(eventTblFieldNames), ",")
	eventTblRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(eventTblFieldNames, "id"))
)

type (
	eventTblModel interface {
		Insert(ctx context.Context, data *EventTbl) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*EventTbl, error)
		Update(ctx context.Context, data *EventTbl) error
		Delete(ctx context.Context, id int64) error
	}

	defaultEventTblModel struct {
		conn  sqlx.SqlConn
		table string
	}

	EventTbl struct {
		Id         int64          `db:"id"`
		Name       string         `db:"name"`
		SchoolYear sql.NullString `db:"school_year"`
		IsCurrent  sql.NullInt64  `db:"is_current"`
	}
)

func newEventTblModel(conn sqlx.SqlConn) *defaultEventTblModel {
	return &defaultEventTblModel{
		conn:  conn,
		table: `"public"."event_tbl"`,
	}
}

func (m *defaultEventTblModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEventTblModel) FindOne(ctx context.Context, id int64) (*EventTbl, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", eventTblRows, m.table)
	var resp EventTbl
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEventTblModel) Insert(ctx context.Context, data *EventTbl) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, eventTblRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.SchoolYear, data.IsCurrent)
	return ret, err
}

func (m *defaultEventTblModel) Update(ctx context.Context, data *EventTbl) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, eventTblRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.SchoolYear, data.IsCurrent)
	return err
}

func (m *defaultEventTblModel) tableName() string {
	return m.table
}
