ALTER TABLE "topic_report_tbl"
ADD COLUMN IF NOT EXISTS "created_at" BIGINT NOT NULL,
ADD COLUMN IF NOT EXISTS "created_by" BIGINT NOT NULL;
ALTER TABLE "topic_mark_tbl"
ADD COLUMN IF NOT EXISTS "level" BIGINT NOT NULL,
ADD COLUMN IF NOT EXISTS "created_at" BIGINT NOT NULL;

ALTER TABLE "subcommittee_tbl"
ADD COLUMN IF NOT EXISTS "level" BIGINT NOT NULL;
ALTER TABLE "topic_tbl"
ADD COLUMN IF NOT EXISTS "estimate_student" bigint NOT NULL;
